### ISSUE TITLE
Potentially invalid string produced for `option = None`

### ISSUE THREAD

**Issue by abravalheri** [pyscaffold/configupdater#68]
## Description of your problem

`ConfigUpdater` seems to potentially generate a file with invalid syntax when `option = None`.
This issue was first reported in pyscaffold/pyscaffold#506.

**Please provide a minimal, self-contained, and reproducible example.**
```python
>>> from tempfile import NamedTemporaryFile
>>> from configupdater import ConfigUpdater
>>> example = """\
... [section]
... opt1 = 42
... """
>>> file = NamedTemporaryFile()
>>> file.write(bytes(example, "utf-8"))
20

>>> file.flush()
>>> cfg = ConfigUpdater().read_file(open(file.name))
>>> str(cfg)
'[section]\nopt1 = 42\n'

>>> cfg['section']['opt2'] = None
>>> str(cfg)
'[section]\nopt1 = 42\nopt2\n'

>>> cfg.update_file()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.8/site-packages/configupdater/configupdater.py", line 172, in update_file
    self.validate_format(**self._parser_opts)
  File ".venv/lib/python3.8/site-packages/configupdater/document.py", line 97, in validate_format
    parser.read_string(str(self))
  File "/usr/lib/python3.8/configparser.py", line 723, in read_string
    self.read_file(sfile, source)
  File "/usr/lib/python3.8/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.8/configparser.py", line 1113, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: '<string>'
        [line  3]: 'opt2\n'

Source contains parsing errors: '<string>'
        [line  3]: 'opt2\n'
```

The same error appears if we simply try to use ConfigUpdater to parse the generated string:
```python
>>> ConfigUpdater().read_string(str(cfg))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.8/site-packages/configupdater/configupdater.py", line 149, in read_string
    return self._parser().read_string(string, source, self)
  File ".venv/lib/python3.8/site-packages/configupdater/parser.py", line 302, in read_string
    return self.read_file(sfile, source, into)
  File ".venv/lib/python3.8/site-packages/configupdater/parser.py", line 278, in read_file
    self._read(f, source, document)
  File ".venv/lib/python3.8/site-packages/configupdater/parser.py", line 516, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: '<string>'
        [line  3]: 'opt2\n'

Source contains parsing errors: '<string>'
        [line  3]: 'opt2\n'
```

**Please provide any additional information below.**

Current Behaviour:
```python
>>> cfg = ConfigUpdater()
>>> cfg.add_section('section')
>>> cfg.set('section', 'opt1', None)
<ConfigUpdater [
    <Section: 'section' [
        <Option: opt1 = None>
    ]>
]>

>>> str(cfg)
'[section]\nopt1\n'
```
If we want to be resilient, I would say the expected behaviour is the following (if `allow_no_value` is set to `False`):
```python
>>> str(cfg)
'[section]\nopt1=\n'
```
(adding a `=` without a value)

Another possibility is to raise an error in `__str__` and tell the user to set `allow_no_value` to `True`.

Anyway, I also advise adding something along the lines:
```python
def validate_format(self, **kwargs):
    return super().validate_format(**{**self._parser_opts, **kwargs})
```
to the `ConfigUpdater` class, to improve consistency.

## Versions and main components

* ConfigUpdater Version: 3.0
* Python Version: 3.8
* Operating system: Ubuntu 18.04 (LTS)
* How did you install ConfigUpdater: pip

**Comment by FlorianWilhelm** [comment]
Thanks, @abravalheri. Just to be sure I got it. Would the fix then reflect what ConfigParser does?
To my understanding:
* Just a key without `=` is always illegal like `key1\n`
* If `allow_no_value = False` then `key1 = \n` raises an error when parsing, right?
*  If `allow_no_value = True` then `key1 = \n` is accepted and value set to None.

Does the fix reflect this? I am not sure about warnings as those are often ignored and hard to programmatically react to warnings if they are no exceptions. This would be a breaking change not in the API but for this special case but it's a fix so I think that would be fine in a bugfix release as it never worked as intended.

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm, please find my considerations bellow:

---
>  Just a key without `=` is always illegal like `key1\n`

If `allow_no_value=True`, this is a legal syntax according to `ConfigParser`:
```python
>>> from configparser import ConfigParser
>>> example = """\
... [section]
... option
... """
cfg = ConfigParser(allow_no_value=True)
>>> cfg.read_string(example)  # no exception
>>> print(repr(cfg["section"]["option"]))
None
```
It is illegal when `allow_no_value=False`:
```pyrhon
>>> cfg = ConfigParser(allow_no_value=False)
>>> cfg.read_string(example)
Traceback (most recent call last):
     ...
configparser.ParsingError: Source contains parsing errors: '<string>'
        [line  2]: 'option\n'

Source contains parsing errors: '<string>'
        [line  2]: 'option\n'
>>>
```
---
> If `allow_no_value = False` then `key1 = \n` raises an error when parsing, right?

I am afraid not, according to `ConfigParser` the value of the option is an empty string:
```python
>>> example = """\
... [section]
... option =
... """
>>> cfg = ConfigParser(allow_no_value=False)
>>> cfg.read_string(example)
>>> print(repr(cfg["section"]["option"]))
''
```
---
> If `allow_no_value = True` then `key1 = \n` is accepted and value set to `None`.

According to `ConfigParser` this syntax is always valid (regardless of `allow_no_value`), but the value associated with the option is an empty string, not `None`.
```python
>>> example = """\
... [section]
... option =
... """
>>> cfg = ConfigParser(allow_no_value=True)
>>> cfg.read_string(example)
>>> print(repr(cfg["section"]["option"]))
''
```

---
PR #70  does not change this overall behaviour of parsing (which was already what `ConfigUpdater` was doing).

What the PR does is to change the behaviour of `Option.__str__` to reflect that...
If merged, `str(<Option: option_name = None>)` will be:
- `allow_no_values = True`: `"option_name"` (without `=`) 
- `allow_no_values = False`: `"option_name ="` + warning for the users asking them to review the kwargs passed to the `ConfigUpdater` instantiation.
  - The isomorphism/bijection here between parsing and converting to string (dumping) is broken (i.e. `None != ""`), but at least we don't raise exceptions that could break applications relying is this dumping behaviour from previous versions of ConfigUpdater.
  - This can be changed to force isomorphism/bijection, but then we have to raise an exception.

The PR changes `ConfigUpdater`  (new `syntax_options` method) expose the syntax parameters, so we can read them in the child classes. The same method is implemented in the `Parser` class, just for the sake of completeness/method parity.

The PR changes the `Section` and `BlockBuilder` to make sure `Option`s are instantiated with the correct `space_around_delimiters` parameter (and there is no inconsistency with the syntax params passed to `ConfigUpdater` constructor).

**Comment by abravalheri** [comment]
I did an interesting comment regarding the isomorphism/bijection between parsing and dumping None/empty string options on pyscaffold/pyscaffold#510:

The INI/CFG format is opaque in terms of the types of the values for the options (i.e. it fundamentally treats them like strings and it is up to the users to interpret those strings how they see fit).

Therefore, does it make sense to enforce this isomorphism/bijection, specially when the user is not interested (did not use `allow_no_values=True` in the constructor)?

We already take the pragmatic approach of considering the INI file opaque for types when we leave the comments as part of the option values...

**Comment by FlorianWilhelm** [comment]
Thanks for writing all the details, this helps a lot. I just tried a bit around with `ConfigParser` too and when `allow_no_values=False` you directly get an error when passing `None`, so
```
cfg = ConfigParser(allow_no_value=False)
cfg.read_string("[abc]")
cfg["abc"]["a"] = None
```
raises `TypeError: option values must be strings`.  Shouldn't we directly reflect that in ConfigUpdater too? Even in a bugfix release? I know it would break things for people abusing this bug right now and expecting it to write an illegal file that cannot be parsed anymore but does this make sense? My gut feeling rather tells me to directly go for an exception as also `ConfigParser` does.

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm, yes I came across the same thing yesterday but I just went for the easy route 😝 

We could do that... We can raise errors at the boundaries, but internally I think it would be difficult to remove all the code that admits `None`, specially because it is parametric according to the syntax parameters.

Or we document that when `allow_no_values=False`, `None` is considered equivalent to an empty string.

In any case, I think most of the ground work for both implementations can rely on #70, since we have to propagate the syntax parameters down to the `Section`, `Option` and `BlockBuilder` classes.
The difference would be checking the syntax parameters on setting option values instead of when converting to string...

**Comment by FlorianWilhelm** [comment]
I think both ways would be valid. I am a bit hesitant to allow things in ConfigUpdater that don't work in ConfigParser. Implicit conversion from `None` to `""`  when `allow_no_values=False` might be what users want in most cases but could also lead to confusion as no one reads the documentation carefully anyway 😝 

That being said, I can live with both ways of solving this, i.e. raising an exception or doing the implicit conversion, also I find the former a bit cleaner as explicit is better than implicit 😉. In the case of the implicit conversion, I think there should be no warning as it is intended behaviour as it is documented or what do you think?

**Comment by abravalheri** [comment]
Hi @FlorianWilhelm, I see your point and I agree with it. I just think it is a laborious task to go through `ConfigUpdater`'s code making sure the code itself does not automatically introduce `option.value = None` (instead of being something done by the user), when `allow_no_values=False`.

The second (minor) point, is that the type annotations would also be "less coherent"... Users would see their IDE's saying that `__setitem__` allows `Union[str, None]` just to be surprised by a runtime error saying that is not really the case. (Since we have to be mindful of the cases when `allow_no_values=True` in the function signatures, I think it is almost impossible to code this in Python's type system — I reckon it would require a [powerful dependent type system](https://en.wikipedia.org/wiki/Dependent_type)).

It might be an oversimplification but the point of adding type annotations is to be able to catch bugs with static analysis, right? In this particular scenario the type system would give a false negative... (We know that `ConfigParser` is not particularly concerned about type consistency and that sometimes it even breaks Liskov substitution principle... So the second argument is not really a concern for the stdlib).

Finally, one alternative approach comes to my mind:
- We could make `Option.__str__() == ''` (empty string) when `allow_no_values=False` (i.e. ignore `None` values)... This way there is no implicit conversion right? We would be just respecting the syntax parameter as defined by the user (it is an opt-out parameter, but nevertheless still a parameter).

**Comment by abravalheri** [comment]
Regarding the `warning`: I agree that we can document this behaviour and not use any warning.

Does it make sense to do this upfront, or use the warning in a sort of *"deprecated behaviour"*/educational way for the current version and then remove the warning in a future release?

Users that are aware of the behaviour and don't mind the implicit conversion/`Option.__str__() == ''` can always [deactivate the warnings](https://docs.python.org/3/library/warnings.html#overriding-the-default-filter) of the `NoneValueDisallowed` category.
